// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbmvegyjaszdkbqrznvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibXZlZ3lqYXN6ZGticXJ6bnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzY0OTgsImV4cCI6MjA3NDU1MjQ5OH0.1lY1vfEz9qaNoHWNGy8TZGf1VjsGog5MLNzkEmbBbfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});